package ru.stonlex.bukkit.gaming.item.menu;

import gnu.trove.map.TIntObjectMap;
import gnu.trove.map.hash.TIntObjectHashMap;
import lombok.NonNull;
import org.bukkit.entity.Player;
import ru.stonlex.bukkit.gaming.item.GamingItemCategory;
import ru.stonlex.bukkit.gaming.player.GamingPlayer;
import ru.stonlex.bukkit.inventory.impl.BaseSimpleInventory;

public abstract class GamingCategoryAutoGeneratedMenu extends BaseSimpleInventory {

    protected final TIntObjectMap<GamingItemCategory> categorySlotMap = new TIntObjectHashMap<>();

    public GamingCategoryAutoGeneratedMenu(int inventoryRows, String inventoryTitle) {
        super(inventoryTitle, inventoryRows);
    }

    @Override
    public void drawInventory(Player player) {
        GamingPlayer gamingPlayer = GamingPlayer.of(player);
        categorySlotMap.forEachEntry((inventorySlot, itemCategory) -> {

            setClickItem(inventorySlot, itemCategory.toBukkitItem(gamingPlayer), (player1, event) ->
                    new GamingItemAutoGeneratedMenu(inventoryRows, itemCategory.getCategoryName(), itemCategory).openInventory(player));

            return true;
        });
    }

    protected void setCategorySlot(int inventorySlot, @NonNull GamingItemCategory itemCategory) {
        categorySlotMap.put(inventorySlot, itemCategory);
    }

}
